[package]
name = "pipette"
version = "0.1.0"
edition = "2018"
authors = ["Jonathan Kelley"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
